### ISSUE TITLE
Breakpoint

### ISSUE THREAD

**Issue by pdav** [sandhose/z33-emulator#12]
Implémenter les breakpoints dans l'interface tty :

- break <addr> : place un point d'arrêt sur l'adresse indiquée
- info breakpoints : liste des points d'arrêts
- continue : lance l'exécution à partir de pc jusqu'au premier point d'arrêt rencontré ou à la première instruction reset

**Comment by sandhose** [comment]
J'ai implémenté les breakpoints (a90514c) ainsi que la commande `list` (f246754). Les breakpoints sont visibles dans la vue `list`, mais je n'ai pas implémenté la commande `info breakpoints` pour l'instant (la raison étant qu'il faudrait que j'adapte l'autocomplétion pour les sous-commandes du genre)

**Comment by sandhose** [comment]
J'ai refactorisé la manière dont je fais l'autocomplétion pour prendre en charge les sous-commandes. Il y a donc maintenant une commande `info breakpoints` pour lister les points d'arrêt.
