### ISSUE TITLE
Initialiser à 0

### ISSUE THREAD

**Issue by pdav** [sandhose/z33-emulator#13]
Initialiser les registres et la mémoire avec des 0 (et non des "Empty")

**Comment by sandhose** [comment]
Il faut savoir que quand on essaie prendre un "word" en mémoire, si la cellule est "empty", elle est castée en "0", cf. https://github.com/sandhose/z33-emulator/blob/b23ca4a24b230ed7e6acc2fbbb3fd1b019f615f6/emulator/src/memory.rs#L63-L64

**Comment by pdav** [comment]
Ce n'est pas transparent au niveau des affichages:

```
run -i ../samples/fact.S main../samples/fact.S main
...
>> r
INFO Registers: %a = empty | %b = empty | %pc = 100 | %sp = 61440 | %sr = (empty)
>> m 1000 2
INFO address=1000 value=empty
INFO address=1001 value=empty
```

Le mieux serait de faire disparaître tous les `empty` et de les remplacer par des valeurs nulles : plus simple, plus conforme à une machine standard, et plus naturel.
