### ISSUE TITLE
Temps relatif

### ISSUE THREAD

**Issue by pdav** [sandhose/z33-emulator#14]
Il faudrait mémoriser un "temps émulé", en fonction des instructions exécutées (cf exo sur le temps d'une primitive système, TD 1).

Ce temps devrait être utilisé :

- par l'utilisateur de l'émulateur pour savoir où il en est (notamment dans le TD 1)
- pour définir un temps pseudo-aléatoire pour simuler une requête disque. Par exemple, une requête prendra `rand()` cycles CPU avant de générer l'interruption de fin

**Comment by sandhose** [comment]
Je viens d'implémenter ça. Le commit 56cccd5 devrait être assez clair sur comment le nombre de cycles est calculé, @pdav 
 je veux bien que tu y jettes in œil pour vérifier que les valeurs que j'ai mises sont les bonnes.
J'ai ajouté une méthode `cost` à `Value` (valeurs immédiates + registre), `Address` (adresse directe, indirecte et indexée), `Reg` (registre) et `Arg` (`Value` ou `Arg`). Il y a ensuite une méthode `cost` sur `Instruction` qui calcule le coût en fonction des arguments de l'instruction.

**Comment by sandhose** [comment]
C'est implémenté depuis un bon bout de temps, et disponible dans l'interface web et en mode interactif
