### ISSUE TITLE
Supprimer les Cargo.lock du dépôt

### ISSUE THREAD

**Issue by pdav** [sandhose/z33-emulator#15]
Les Cargo.lock n'ont pas vocation à faire partie du dépôt, et empêchent un "git pull" de fonctionner correctement.

**Comment by sandhose** [comment]
J'ai trouvé ça dans la doc de Cargo: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

J'ai mis à jour le lockfile (`cargo generate-lockfile`), il ne devrait plus te poser problème.
