### ISSUE TITLE
Disposition en mémoire

### ISSUE THREAD

**Issue by sandhose** [sandhose/z33-emulator#2]
La spec utilise:

 - l'adresse 200 pour le handler d'interruptions
 - les adresses 100+ pour sauvegarder des valeurs pendant les interruptions
 
Il faut probablement aussi définir une valeur par défaut pour le début du programme (300 ?) et le début de la pile (10000 ?)

**Comment by pdav** [comment]
Le processeur est initialisé avec tous les registres à 0.
Le code entre 0 et 99 doit être considéré comme une ROM contenant un programme (reste à définir ce qu'il fait...).
