### ISSUE TITLE
Mode superviseur et instructions invalides

### ISSUE THREAD

**Issue by sandhose** [sandhose/z33-emulator#3]
Le mode utilisateur doit empêcher d'exécuter certaines instructions, notamment : 

 - modifier `%sr`
 - `rti` ?
 - modifier certaines adresse ? là où il y a le handler d'interruption ? les adresses contenant des instructions ?
- autre chose ?

**Comment by pdav** [comment]
- `rti` : c'est effectivement une instruction privilégiée
- modifier certaines adresses : c'est uniquement fonction de la variante (Z33-M, Z33-S, Z33-V), sachant que le Z33-tout-court n'a pas d'adresse interdite (sauf peut-être la ROM qu'il faudra implémenter)
- instructions d'E/S : `in` et `out`
