### ISSUE TITLE
Flag Z in SR is not updated

### ISSUE THREAD

**Issue by pdav** [sandhose/z33-emulator#773]
When a value 0 is loaded in a register (after a ld instruction or after any ALU instruction), the Z flag in SR is not set to 1.

**Comment by sandhose** [comment]
The only case where we see the Z flag is with the cmp instruction: https://github.com/sandhose/z33-emulator/blob/main/emulator/src/runtime/instructions.rs#L193

I'm not sure I understand what other instructions would affect it?
